### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by srinathganesh** [eduardomota/dockerfiles#1]
I used the default docker compose and .env files, and after resiger user it crashed. should I post to OWA main page? or anything wrong at docker?

```
open-web-analytics | NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/html/owa_db.php on line 356
open-web-analytics | NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/html/owa_db.php on line 356
open-web-analytics | NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/html/owa_db.php on line 356
open-web-analytics | NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/html/owa_db.php on line 356
open-web-analytics | NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/html/owa_db.php on line 356
open-web-analytics | 2021/03/30 02:59:00 [error] 16#16: *20 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.96.1, server: _, request: "POST /install.php?owa_site_id=&owa_do=base.installDefaultsEntry& HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "0.0.0.0:8080", referrer: "http://0.0.0.0:8080/install.php?owa_site_id=&owa_do=base.installDefaultsEntry&"
open-web-analytics | 192.168.96.1 - - [30/Mar/2021:02:59:00 +0000] "POST /install.php?owa_site_id=&owa_do=base.installDefaultsEntry& HTTP/1.1" 404 556 "http://0.0.0.0:8080/install.php?owa_site_id=&owa_do=base.installDefaultsEntry&" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
open-web-analytics | 2021/03/30 02:59:00 [error] 16#16: *20 open() "/var/lib/nginx/html/50x.html" failed (2: No such file or directory), client: 192.168.96.1, server: _, request: "POST /install.php?owa_site_id=&owa_do=base.installDefaultsEntry& HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "0.0.0.0:8080", referrer: "http://0.0.0.0:8080/install.php?owa_site_id=&owa_do=base.installDefaultsEntry&"
open-web-analytics | NOTICE: PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/owa_base.php on line 99
```

**Comment by supermarsx** [comment]
Hi srinathganesh,

i've tested through your issue, it seems to be some sort of OWA error, kinda like explained here,
https://github.com/Open-Web-Analytics/Open-Web-Analytics/issues/71

I suppose your error shows after successful install, you're unable to login with your correct credentials. I've had this issue with Chrome and Edge, the only working browser is Firefox, these OWA docker images are based off the official application distributions nginx, php-fpm and owa.

To make sure it wasn't something else i've built 3 flavors from scratch again with php 7.3, 7.4 e 8.0. Always the same results, you can try it and even build images from scratch using the provided Dockerfiles.

Please try to be crystal clear when exposing problems so people understand what you're saying.

Other things you may try if it's still not solved:
- Put the container behind another reverse proxy and point a domain to it, like Internet <-> Nginx reverse proxy (nginx manager) <-> owa nginx stack.
- Try enabling debug mode and go deeper, https://github.com/Open-Web-Analytics/Open-Web-Analytics/blob/master/owa-config-dist.php (for reference)

Cheers and happy dockering
